# Generated by ChatGPT on 2026-03-01

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('socio', 'Sócio'), ('advogado', 'Advogado'), ('assistente', 'Assistente'), ('financeiro', 'Financeiro'), ('cliente', 'Cliente')], max_length=20)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.tenant')),
            ],
            options={},
        ),
        migrations.AddIndex(
            model_name='tenantinvite',
            index=models.Index(fields=['tenant', 'email'], name='accounts_tenant_email_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvite',
            index=models.Index(fields=['token'], name='accounts_invite_token_idx'),
        ),
    ]
