# Generated by Django 5.2.11 on 2026-03-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_lgpd'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantinvite',
            new_name='accounts_te_tenant__11dded_idx',
            old_name='accounts_tenant_email_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantinvite',
            new_name='accounts_te_token_a143df_idx',
            old_name='accounts_invite_token_idx',
        ),
        migrations.AlterField(
            model_name='tenantinvite',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('LAWYER', 'Lawyer'), ('ASSISTANT', 'Assistant'), ('FINANCE', 'Finance'), ('CLIENT', 'Client')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('LAWYER', 'Lawyer'), ('ASSISTANT', 'Assistant'), ('FINANCE', 'Finance'), ('CLIENT', 'Client')], max_length=20),
        ),
    ]
