# Generated by Django 5.2.11 on 2026-03-04 23:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useraccesspermission'),
        ('core', '0004_rename_core_audite_tenant__db4ce2_idx_core_audite_tenant__b7d570_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_positions', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('document_id', models.CharField(blank=True, max_length=32, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.employeeposition')),
            ],
        ),
        migrations.AddIndex(
            model_name='employeeposition',
            index=models.Index(fields=['tenant', 'name'], name='accounts_em_tenant__e1cf9b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeposition',
            index=models.Index(fields=['tenant', 'is_active'], name='accounts_em_tenant__11242c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeposition',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'full_name'], name='accounts_em_tenant__9f888b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'is_active'], name='accounts_em_tenant__977576_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'position'], name='accounts_em_tenant__df2dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'document_id'], name='accounts_em_tenant__3854ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('tenant', 'user')},
        ),
    ]
