# Generated by Django 5.2.11 on 2026-03-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employeeposition_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
