# Generated by Django 5.2.11 on 2026-03-05 01:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_employee_salario_employeeposition_salario_base'),
        ('core', '0004_rename_core_audite_tenant__db4ce2_idx_core_audite_tenant__b7d570_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='accounts.department'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'department'], name='accounts_em_tenant__79a615_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'name'], name='accounts_de_tenant__657fda_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'is_active'], name='accounts_de_tenant__0c9a54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant', 'name')},
        ),
    ]
