# Generated by Django 5.2.11 on 2026-03-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_department_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeposition',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
