# Generated by Django 5.2.15 on 2026-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_employee_accounts_em_tenant__79a615_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="notification_prefs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="oab",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
