# Generated by ChatGPT on 2026-03-01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
