# Generated by Django 5.2.11 on 2026-03-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audit_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='core_audite_tenant__b7d570_idx',
            old_name='core_audite_tenant__db4ce2_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='core_audite_tenant__9aff8e_idx',
            old_name='core_audite_tenant__8f69aa_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='core_audite_tenant__8e497e_idx',
            old_name='core_audite_tenant__4680c3_idx',
        ),
    ]
