# Generated by Django 5.2.11 on 2026-03-07 15:52

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_core_audite_tenant__db4ce2_idx_core_audite_tenant__b7d570_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_published', models.BooleanField(default=False)),
                ('brand_name', models.CharField(blank=True, default='', max_length=255)),
                ('hero_title', models.CharField(blank=True, default='', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='')),
                ('primary_cta_label', models.CharField(blank=True, default='Agendar Consulta', max_length=120)),
                ('primary_cta_url', models.CharField(blank=True, default='#contato', max_length=255)),
                ('secondary_cta_label', models.CharField(blank=True, default='Falar no WhatsApp', max_length=120)),
                ('secondary_cta_url', models.CharField(blank=True, default='#contato', max_length=255)),
                ('areas', models.JSONField(blank=True, default=apps.core.models.default_landing_areas)),
                ('differentials', models.JSONField(blank=True, default=apps.core.models.default_landing_differentials)),
                ('testimonials', models.JSONField(blank=True, default=list)),
                ('team', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_address', models.CharField(blank=True, default='', max_length=255)),
                ('contact_whatsapp', models.CharField(blank=True, default='', max_length=50)),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.CharField(blank=True, default='', max_length=300)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_landing_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingLead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='landing_contact', max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_leads', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='core_landin_tenant__c84ea7_idx'), models.Index(fields=['tenant', 'email'], name='core_landin_tenant__8d0e81_idx')],
            },
        ),
    ]
