# Generated by Django 5.2.12 on 2026-03-12 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_calendarevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="calendarevent",
            new_name="core_calend_tenant__2e37ac_idx",
            old_name="core_calend_tenant__start_a_4b2286_idx",
        ),
        migrations.RenameIndex(
            model_name="calendarevent",
            new_name="core_calend_tenant__340b7b_idx",
            old_name="core_calend_tenant__kind_74072b_idx",
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
