# Generated by Codex on 2026-03-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_rename_core_calend_tenant__start_a_4b2286_idx_core_calend_tenant__2e37ac_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=64)),
                ('scope_key', models.CharField(blank=True, default='', max_length=128)),
                ('item_key', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_states', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_workspace_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['namespace', 'scope_key', 'item_key'],
                'unique_together': {('tenant', 'namespace', 'scope_key', 'item_key')},
            },
        ),
        migrations.AddIndex(
            model_name='workspacestate',
            index=models.Index(fields=['tenant', 'namespace', 'scope_key'], name='core_worksp_tenant__038482_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacestate',
            index=models.Index(fields=['tenant', 'namespace', 'updated_at'], name='core_worksp_tenant__1c0450_idx'),
        ),
    ]
