# Generated by Django 5.2.12 on 2026-03-27 17:04

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_workspacestate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingBlogPost",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, default="")),
                ("content", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.models.landing_asset_upload_to,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "seo_description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["sort_order", "-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandingDifferential",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("icon", models.CharField(blank=True, default="Shield", max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandingLeadDeliveryLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound_notification", "Inbound notification"),
                            ("outbound_reply", "Outbound reply"),
                        ],
                        max_length=32,
                    ),
                ),
                ("channel", models.CharField(default="email", max_length=32)),
                ("recipient", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandingNavigationLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("url", models.CharField(max_length=255)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("HEADER", "Header"),
                            ("FOOTER", "Footer"),
                            ("BOTH", "Both"),
                        ],
                        default="BOTH",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandingProcessStep",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, default="CheckCircle2", max_length=64),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandingSiteSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "brand_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "brand_tagline",
                    models.CharField(
                        blank=True, default="Advocacia especializada", max_length=255
                    ),
                ),
                ("theme", models.JSONField(blank=True, default=dict)),
                ("hero_enabled", models.BooleanField(default=True)),
                (
                    "hero_subtitle",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "hero_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("hero_description", models.TextField(blank=True, default="")),
                (
                    "hero_primary_cta_label",
                    models.CharField(
                        blank=True, default="Fale com a equipe", max_length=120
                    ),
                ),
                (
                    "hero_primary_cta_url",
                    models.CharField(blank=True, default="#contato", max_length=255),
                ),
                (
                    "hero_background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.models.landing_asset_upload_to,
                    ),
                ),
                (
                    "hero_overlay_color",
                    models.CharField(blank=True, default="#081d36", max_length=30),
                ),
                (
                    "hero_overlay_opacity",
                    models.DecimalField(decimal_places=2, default=0.74, max_digits=4),
                ),
                ("services_enabled", models.BooleanField(default=True)),
                (
                    "services_eyebrow",
                    models.CharField(
                        blank=True, default="O que nos fazemos", max_length=255
                    ),
                ),
                (
                    "services_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("services_description", models.TextField(blank=True, default="")),
                (
                    "services_button_text",
                    models.CharField(
                        blank=True, default="Fale pelo WhatsApp", max_length=120
                    ),
                ),
                ("about_enabled", models.BooleanField(default=True)),
                (
                    "about_eyebrow",
                    models.CharField(
                        blank=True, default="Escritorio de Advocacia", max_length=255
                    ),
                ),
                (
                    "about_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "about_highlight",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("about_description", models.TextField(blank=True, default="")),
                (
                    "about_secondary_description",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "about_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.models.landing_asset_upload_to,
                    ),
                ),
                ("differentials_enabled", models.BooleanField(default=True)),
                (
                    "differentials_eyebrow",
                    models.CharField(
                        blank=True, default="Porque escolher-nos", max_length=255
                    ),
                ),
                (
                    "differentials_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("differentials_description", models.TextField(blank=True, default="")),
                ("contact_enabled", models.BooleanField(default=True)),
                (
                    "contact_eyebrow",
                    models.CharField(
                        blank=True, default="Entre em Contato", max_length=255
                    ),
                ),
                (
                    "contact_title",
                    models.CharField(
                        blank=True, default="Fale com a equipe", max_length=255
                    ),
                ),
                ("contact_description", models.TextField(blank=True, default="")),
                (
                    "contact_button_text",
                    models.CharField(
                        blank=True, default="Enviar mensagem", max_length=120
                    ),
                ),
                (
                    "contact_success_message",
                    models.CharField(
                        blank=True,
                        default="Mensagem enviada com sucesso.",
                        max_length=255,
                    ),
                ),
                ("contact_recipient_emails", models.TextField(blank=True, default="")),
                ("contact_send_email", models.BooleanField(default=True)),
                ("process_enabled", models.BooleanField(default=True)),
                (
                    "process_eyebrow",
                    models.CharField(
                        blank=True, default="Como isso funciona", max_length=255
                    ),
                ),
                (
                    "process_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("process_description", models.TextField(blank=True, default="")),
                ("blog_enabled", models.BooleanField(default=True)),
                (
                    "blog_eyebrow",
                    models.CharField(
                        blank=True, default="Artigos e informativos", max_length=255
                    ),
                ),
                (
                    "blog_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("blog_description", models.TextField(blank=True, default="")),
                (
                    "blog_button_text",
                    models.CharField(blank=True, default="Veja mais", max_length=120),
                ),
                (
                    "blog_button_url",
                    models.CharField(blank=True, default="#artigos", max_length=255),
                ),
                ("testimonials_enabled", models.BooleanField(default=True)),
                (
                    "testimonials_eyebrow",
                    models.CharField(blank=True, default="Depoimentos", max_length=255),
                ),
                (
                    "testimonials_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("map_enabled", models.BooleanField(default=True)),
                (
                    "map_embed_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("final_cta_enabled", models.BooleanField(default=True)),
                (
                    "final_cta_eyebrow",
                    models.CharField(
                        blank=True, default="Precisa de ajuda?", max_length=255
                    ),
                ),
                (
                    "final_cta_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("final_cta_description", models.TextField(blank=True, default="")),
                (
                    "final_cta_button_text",
                    models.CharField(
                        blank=True, default="Fale pelo WhatsApp", max_length=120
                    ),
                ),
                (
                    "final_cta_button_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "final_cta_background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.models.landing_asset_upload_to,
                    ),
                ),
                ("footer_enabled", models.BooleanField(default=True)),
                ("footer_description", models.TextField(blank=True, default="")),
                (
                    "footer_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "footer_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "footer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "footer_copyright",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "client_portal_label",
                    models.CharField(
                        blank=True, default="Area do Cliente", max_length=120
                    ),
                ),
                (
                    "client_portal_url",
                    models.CharField(
                        blank=True, default="/portal/login", max_length=255
                    ),
                ),
                (
                    "internal_area_label",
                    models.CharField(
                        blank=True, default="Area Interna", max_length=120
                    ),
                ),
                (
                    "internal_area_url",
                    models.CharField(blank=True, default="/app/login", max_length=255),
                ),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "seo_description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "seo_keywords",
                    models.CharField(blank=True, default="", max_length=300),
                ),
            ],
            options={
                "verbose_name": "Landing Site Settings",
                "verbose_name_plural": "Landing Site Settings",
            },
        ),
        migrations.CreateModel(
            name="LandingSocialLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("url", models.CharField(max_length=255)),
                ("icon", models.CharField(blank=True, default="Globe", max_length=64)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandingTestimonial",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, default="", max_length=255)),
                ("text", models.TextField(blank=True, default="")),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="workspacestate",
            new_name="core_worksp_tenant__532d05_idx",
            old_name="core_worksp_tenant__038482_idx",
        ),
        migrations.RenameIndex(
            model_name="workspacestate",
            new_name="core_worksp_tenant__43be60_idx",
            old_name="core_worksp_tenant__1c0450_idx",
        ),
        migrations.AddField(
            model_name="landinglead",
            name="email_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="is_spam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="recipient_email",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responded_landing_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="response_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="spam_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Novo"),
                    ("read", "Lido"),
                    ("responded", "Respondido"),
                    ("spam", "Spam"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="user_agent",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="kind",
            field=models.CharField(
                choices=[("EVENT", "Evento"), ("HEARING", "Audiencia")],
                default="EVENT",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="landinglead",
            index=models.Index(
                fields=["tenant", "status", "created_at"],
                name="core_landin_tenant__2035c0_idx",
            ),
        ),
        migrations.AddField(
            model_name="landingblogpost",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landing_blog_posts",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="landingdifferential",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landing_differentials",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="landingleaddeliverylog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_landing_lead_delivery_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="landingleaddeliverylog",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_logs",
                to="core.landinglead",
            ),
        ),
        migrations.AddField(
            model_name="landingleaddeliverylog",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landing_lead_delivery_logs",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="landingnavigationlink",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landing_navigation_links",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="landingprocessstep",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landing_process_steps",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="landingsitesettings",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landing_site_settings",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="landingsitesettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_landing_site_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="landingsociallink",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landing_social_links",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="landingtestimonial",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landing_testimonials",
                to="core.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="landingblogpost",
            index=models.Index(
                fields=["tenant", "is_published", "published_at"],
                name="core_landin_tenant__9f0cd7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="landingblogpost",
            index=models.Index(
                fields=["tenant", "slug"], name="core_landin_tenant__d7748a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="landingblogpost",
            unique_together={("tenant", "slug")},
        ),
        migrations.AddIndex(
            model_name="landingdifferential",
            index=models.Index(
                fields=["tenant", "sort_order"], name="core_landin_tenant__9047f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landingdifferential",
            index=models.Index(
                fields=["tenant", "is_active"], name="core_landin_tenant__5fae26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landingleaddeliverylog",
            index=models.Index(
                fields=["tenant", "created_at"], name="core_landin_tenant__741b15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landingleaddeliverylog",
            index=models.Index(
                fields=["lead", "created_at"], name="core_landin_lead_id_0ab774_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landingnavigationlink",
            index=models.Index(
                fields=["tenant", "location", "sort_order"],
                name="core_landin_tenant__79705b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="landingnavigationlink",
            index=models.Index(
                fields=["tenant", "is_active"], name="core_landin_tenant__4cde87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landingprocessstep",
            index=models.Index(
                fields=["tenant", "sort_order"], name="core_landin_tenant__114877_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landingprocessstep",
            index=models.Index(
                fields=["tenant", "is_active"], name="core_landin_tenant__24522c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landingsociallink",
            index=models.Index(
                fields=["tenant", "sort_order"], name="core_landin_tenant__4caa8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landingsociallink",
            index=models.Index(
                fields=["tenant", "is_active"], name="core_landin_tenant__c5d795_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landingtestimonial",
            index=models.Index(
                fields=["tenant", "sort_order"], name="core_landin_tenant__863f7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landingtestimonial",
            index=models.Index(
                fields=["tenant", "is_active"], name="core_landin_tenant__837d6a_idx"
            ),
        ),
    ]
