# Generated by Django 5.2.15 on 2026-06-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_landingblogpost_landingdifferential_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingsitesettings",
            name="about_eyebrow",
            field=models.CharField(
                blank=True, default="Sobre o escritório", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="landingsitesettings",
            name="contact_title",
            field=models.CharField(
                blank=True, default="Agendar consulta", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="landingsitesettings",
            name="differentials_eyebrow",
            field=models.CharField(
                blank=True, default="Nossos diferenciais", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="landingsitesettings",
            name="hero_primary_cta_label",
            field=models.CharField(
                blank=True, default="Agendar consulta", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="landingsitesettings",
            name="process_eyebrow",
            field=models.CharField(
                blank=True, default="Etapas do atendimento", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="landingsitesettings",
            name="services_eyebrow",
            field=models.CharField(
                blank=True, default="Áreas de atuação", max_length=255
            ),
        ),
    ]
