# Generated by Django 5.2.15 on 2026-07-03 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_task_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Nulo para eventos de conta (login/logout) anteriores à seleção de tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_events",
                to="core.tenant",
            ),
        ),
    ]
