# Generated by Django 5.2.15 on 2026-07-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_auditevent_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "Sem recorrência"),
                    ("daily", "Diária"),
                    ("weekly", "Semanal"),
                    ("monthly", "Mensal"),
                    ("yearly", "Anual"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_until",
            field=models.DateField(
                blank=True,
                help_text="Última data em que a recorrência gera ocorrência.",
                null=True,
            ),
        ),
    ]
