from __future__ import annotations

# Canonical permission codes expected by the admin portal UI.
ACCESS_PERMISSION_CODES = [
    "cause.view",
    "cause.create",
    "cause.update",
    "cause.delete",
    "position.view",
    "position.create",
    "position.update",
    "position.delete",
    "employee.view",
    "employee.create",
    "employee.update",
    "employee.delete",
    "process.view",
    "process.create",
    "process.update",
    "process.delete",
    "finance.view",
    "finance.create",
    "finance.issue",
    "finance.invoice",
    "client.view",
    "client.create",
    "client.update",
    "client.delete",
    "admin.manage_users",
    "admin.audit",
    "admin.settings",
    "knowledge.view",
    "knowledge.create",
    "portal.view",
]
