# Generated by ChatGPT on 2026-03-01

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_normalization'),
        ('core', '0001_initial'),
        ('documents', '0002_document_storage_roles_versioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalTemplate',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('group_id', models.UUIDField(default=uuid.uuid4, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='geral', max_length=120)),
                ('format', models.CharField(choices=[('RICH_TEXT', 'Rich text'), ('PLAIN_TEXT', 'Plain text')], default='RICH_TEXT', max_length=20)),
                ('content', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('access_level', models.CharField(choices=[('TENANT', 'Tenant'), ('ROLES', 'Roles')], default='TENANT', max_length=16)),
                ('allowed_roles', models.JSONField(default=list, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to='accounts.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_templates', to='accounts.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_templates', to='core.tenant')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['tenant', 'created_at'], name='documents_le_tenant__c6fb12_idx'),
                    models.Index(fields=['tenant', 'group_id'], name='documents_le_tenant__0c1c1c_idx'),
                    models.Index(fields=['tenant', 'category', 'created_at'], name='documents_le_tenant__b77114_idx'),
                ],
            },
        ),
    ]
