# Generated by Django 5.2.11 on 2026-03-02 00:09

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_tenant__1bffd8_idx',
            old_name='documents_do_tenant__53f0f0_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_tenant__cf0145_idx',
            old_name='documents_do_tenant__0d5f3c_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_tenant__b0b839_idx',
            old_name='documents_do_tenant__f0b4f4_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_tenant__fb79d6_idx',
            old_name='documents_do_tenant__f1a365_idx',
        ),
        migrations.RenameIndex(
            model_name='legaltemplate',
            new_name='documents_l_tenant__efabad_idx',
            old_name='documents_le_tenant__c6fb12_idx',
        ),
        migrations.RenameIndex(
            model_name='legaltemplate',
            new_name='documents_l_tenant__463df9_idx',
            old_name='documents_le_tenant__0c1c1c_idx',
        ),
        migrations.RenameIndex(
            model_name='legaltemplate',
            new_name='documents_l_tenant__977b9b_idx',
            old_name='documents_le_tenant__b77114_idx',
        ),
        migrations.AddField(
            model_name='contract',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', related_query_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', related_query_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legaltemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='legaltemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', related_query_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', related_query_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.documents.models.document_upload_to),
        ),
    ]
