# Generated by Django 5.2.11 on 2026-03-07 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_soft_delete'),
        ('core', '0005_landingpage_landinglead'),
        ('documents', '0005_rename_documents_do_tenant__53f0f0_idx_documents_d_tenant__1bffd8_idx_and_more'),
        ('processes', '0007_legalcause_process_cause_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessRichDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='peticao', max_length=120)),
                ('content_html', models.TextField(blank=True, default='')),
                ('version', models.IntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=16)),
                ('access_level', models.CharField(choices=[('TENANT', 'Tenant'), ('ROLES', 'Roles')], default='TENANT', max_length=16)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rich_documents', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rich_documents', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', related_query_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rich_documents', to='processes.process')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_rich_documents', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rich_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='documents_p_tenant__c149bc_idx'), models.Index(fields=['tenant', 'group_id'], name='documents_p_tenant__250882_idx'), models.Index(fields=['tenant', 'process', 'created_at'], name='documents_p_tenant__6e6b37_idx'), models.Index(fields=['tenant', 'client', 'created_at'], name='documents_p_tenant__77c392_idx'), models.Index(fields=['tenant', 'status', 'created_at'], name='documents_p_tenant__8da42e_idx')],
            },
        ),
    ]
