# Generated by Django 5.2.11 on 2026-03-07 16:41

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_processrichdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.documents.models.document_upload_to),
        ),
    ]
