# Generated by Django 5.2.11 on 2026-02-28 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnj', models.CharField(blank=True, max_length=60, null=True)),
                ('court', models.CharField(blank=True, max_length=255, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=255, null=True)),
                ('court_division', models.CharField(blank=True, max_length=255, null=True)),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(choices=[('civel', 'Cível'), ('trabalhista', 'Trabalhista'), ('criminal', 'Criminal'), ('tributario', 'Tributário'), ('empresarial', 'Empresarial'), ('familia', 'Família'), ('consumidor', 'Consumidor')], default='civel', max_length=20)),
                ('phase', models.CharField(choices=[('conhecimento', 'Conhecimento'), ('recursal', 'Recursal'), ('execucao', 'Execução'), ('cumprimento', 'Cumprimento')], default='conhecimento', max_length=20)),
                ('status', models.CharField(choices=[('pre_processual', 'Pré-processual'), ('em_andamento', 'Em andamento'), ('suspenso', 'Suspenso'), ('finalizado', 'Finalizado'), ('arquivado', 'Arquivado')], default='em_andamento', max_length=20)),
                ('cause_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('probability', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('plaintiff', models.CharField(blank=True, max_length=255, null=True)),
                ('defendant', models.CharField(blank=True, max_length=255, null=True)),
                ('team_members', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='clients.client')),
                ('responsible_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_processes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('despacho', 'Despacho'), ('decisao', 'Decisão'), ('sentenca', 'Sentença'), ('peticao', 'Petição'), ('audiencia', 'Audiência'), ('publicacao', 'Publicação'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.tenant')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='processes.process')),
            ],
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('hearing_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('online_link', models.URLField(blank=True, null=True)),
                ('modality', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrida', 'Híbrida')], default='presencial', max_length=12)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('redesignada', 'Redesignada'), ('cancelada', 'Cancelada')], default='agendada', max_length=12)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearings', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='core.tenant')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='processes.process')),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('atrasado', 'Atrasado')], default='pendente', max_length=10)),
                ('alert_channels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlines', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='core.tenant')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='processes.process')),
            ],
        ),
    ]
