# Generated by ChatGPT on 2026-03-01
import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
        ('core', '0003_audit_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_hours', models.IntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='processes.deadline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_alerts', to='core.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='deadlinealert',
            index=models.Index(fields=['tenant', 'sent_at'], name='processes_d_tenant__a03c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='deadlinealert',
            index=models.Index(fields=['deadline', 'window_hours'], name='processes_d_deadlin_3e52ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deadlinealert',
            unique_together={('deadline', 'window_hours')},
        ),
    ]
