# Generated by ChatGPT on 2026-03-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_processes_indexes_pr10'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='process',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deadlines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_deadlines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hearing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hearings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hearing',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hearings', to=settings.AUTH_USER_MODEL),
        ),
    ]
