# Generated by Django 5.2.11 on 2026-03-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_soft_delete_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deadline',
            new_name='processes_d_tenant__022f83_idx',
            old_name='dl_tenant_status_due',
        ),
        migrations.RenameIndex(
            model_name='deadline',
            new_name='processes_d_tenant__78e7b1_idx',
            old_name='dl_tenant_process_due',
        ),
        migrations.RenameIndex(
            model_name='deadline',
            new_name='processes_d_tenant__669f39_idx',
            old_name='dl_tenant_created',
        ),
        migrations.RenameIndex(
            model_name='deadlinealert',
            new_name='processes_d_tenant__f3fa25_idx',
            old_name='processes_d_tenant__a03c3f_idx',
        ),
        migrations.RenameIndex(
            model_name='deadlinealert',
            new_name='processes_d_deadlin_56cb58_idx',
            old_name='processes_d_deadlin_3e52ee_idx',
        ),
        migrations.RenameIndex(
            model_name='hearing',
            new_name='processes_h_tenant__35d2e6_idx',
            old_name='hear_tenant_status_date',
        ),
        migrations.RenameIndex(
            model_name='hearing',
            new_name='processes_h_tenant__d0fe40_idx',
            old_name='hear_tenant_process_date',
        ),
        migrations.RenameIndex(
            model_name='hearing',
            new_name='processes_h_tenant__3d0a88_idx',
            old_name='hear_tenant_created',
        ),
        migrations.RenameIndex(
            model_name='movement',
            new_name='processes_m_tenant__a20621_idx',
            old_name='mov_tenant_process_date',
        ),
        migrations.RenameIndex(
            model_name='movement',
            new_name='processes_m_tenant__409333_idx',
            old_name='mov_tenant_created',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='processes_p_tenant__0b91bc_idx',
            old_name='proc_tenant_status_created',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='processes_p_tenant__ae389f_idx',
            old_name='proc_tenant_updated',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='processes_p_tenant__b861ed_idx',
            old_name='proc_tenant_cnj',
        ),
    ]
