# Generated by Django 5.2.11 on 2026-03-07 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_soft_delete'),
        ('core', '0004_rename_core_audite_tenant__db4ce2_idx_core_audite_tenant__b7d570_idx_and_more'),
        ('processes', '0006_rename_dl_tenant_status_due_processes_d_tenant__022f83_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(choices=[('civel', 'Cível'), ('trabalhista', 'Trabalhista'), ('criminal', 'Criminal'), ('tributario', 'Tributário'), ('empresarial', 'Empresarial'), ('familia', 'Família'), ('consumidor', 'Consumidor')], default='civel', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_causes', to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='processes.legalcause'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['tenant', 'cause'], name='processes_p_tenant__7cd10e_idx'),
        ),
        migrations.AddIndex(
            model_name='legalcause',
            index=models.Index(fields=['tenant', 'name'], name='processes_l_tenant__e07d29_idx'),
        ),
        migrations.AddIndex(
            model_name='legalcause',
            index=models.Index(fields=['tenant', 'area'], name='processes_l_tenant__af83f3_idx'),
        ),
        migrations.AddIndex(
            model_name='legalcause',
            index=models.Index(fields=['tenant', 'is_active'], name='processes_l_tenant__833d0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='legalcause',
            unique_together={('tenant', 'name')},
        ),
    ]
