# Generated by Django 5.2.12 on 2026-03-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_landingblogpost_landingdifferential_and_more"),
        ("processes", "0007_legalcause_process_cause_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legalcause",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.AddField(
            model_name="legalcause",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="legalcause",
            name="landing_icon",
            field=models.CharField(blank=True, default="Scale", max_length=64),
        ),
        migrations.AddField(
            model_name="legalcause",
            name="landing_link",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="legalcause",
            name="show_on_landing",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="deadline",
            name="priority",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("media", "Media"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="media",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="deadline",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("concluido", "Concluido"),
                    ("atrasado", "Atrasado"),
                ],
                default="pendente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="hearing",
            name="modality",
            field=models.CharField(
                choices=[
                    ("presencial", "Presencial"),
                    ("online", "Online"),
                    ("hibrida", "Hibrida"),
                ],
                default="presencial",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="legalcause",
            name="area",
            field=models.CharField(
                choices=[
                    ("civel", "Civel"),
                    ("trabalhista", "Trabalhista"),
                    ("criminal", "Criminal"),
                    ("tributario", "Tributario"),
                    ("empresarial", "Empresarial"),
                    ("familia", "Familia"),
                    ("consumidor", "Consumidor"),
                ],
                default="civel",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="movement",
            name="type",
            field=models.CharField(
                choices=[
                    ("despacho", "Despacho"),
                    ("decisao", "Decisao"),
                    ("sentenca", "Sentenca"),
                    ("peticao", "Peticao"),
                    ("audiencia", "Audiencia"),
                    ("publicacao", "Publicacao"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="area",
            field=models.CharField(
                choices=[
                    ("civel", "Civel"),
                    ("trabalhista", "Trabalhista"),
                    ("criminal", "Criminal"),
                    ("tributario", "Tributario"),
                    ("empresarial", "Empresarial"),
                    ("familia", "Familia"),
                    ("consumidor", "Consumidor"),
                ],
                default="civel",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="phase",
            field=models.CharField(
                choices=[
                    ("conhecimento", "Conhecimento"),
                    ("recursal", "Recursal"),
                    ("execucao", "Execucao"),
                    ("cumprimento", "Cumprimento"),
                ],
                default="conhecimento",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="probability",
            field=models.CharField(
                choices=[("baixa", "Baixa"), ("media", "Media"), ("alta", "Alta")],
                default="media",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre_processual", "Pre-processual"),
                    ("em_andamento", "Em andamento"),
                    ("suspenso", "Suspenso"),
                    ("finalizado", "Finalizado"),
                    ("arquivado", "Arquivado"),
                ],
                default="em_andamento",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="legalcause",
            index=models.Index(
                fields=["tenant", "show_on_landing", "display_order"],
                name="processes_l_tenant__909c35_idx",
            ),
        ),
    ]
