# Generated by Django 5.2.15 on 2026-07-03 04:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


TABLE = "processes_tribunalsync"

# (old_name, new_name, columns) — mesmos índices definidos em 0011.
_INDEX_RENAMES = [
    ("processes_tr_tenant_process_idx", "processes_t_tenant__6d72e9_idx", ("tenant_id", "process_id")),
    ("processes_tr_tenant_syncstatus_idx", "processes_t_tenant__4c2603_idx", ("tenant_id", "sync_status")),
]


def _existing_indexes(schema_editor):
    with schema_editor.connection.cursor() as cursor:
        return {
            name
            for name, info in schema_editor.connection.introspection.get_constraints(
                cursor, TABLE
            ).items()
            if info.get("index")
        }


def _rename_indexes_forward(apps, schema_editor):
    """Renomeia os índices de forma idempotente.

    Em SQLite, uma reconstrução de tabela (feita por migrações anteriores)
    pode ter recriado os índices com o nome auto-gerado do Django, deixando
    o nome explícito de 0011 ausente. Aqui garantimos o estado final sem
    falhar caso o índice antigo não exista.
    """
    existing = _existing_indexes(schema_editor)
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name, columns in _INDEX_RENAMES:
            if new_name in existing:
                continue
            if old_name in existing:
                cursor.execute(f"DROP INDEX {quote(old_name)}")
            cols = ", ".join(quote(c) for c in columns)
            cursor.execute(f"CREATE INDEX {quote(new_name)} ON {quote(TABLE)} ({cols})")


def _rename_indexes_backward(apps, schema_editor):
    existing = _existing_indexes(schema_editor)
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name, columns in _INDEX_RENAMES:
            if old_name in existing:
                continue
            if new_name in existing:
                cursor.execute(f"DROP INDEX {quote(new_name)}")
            cols = ", ".join(quote(c) for c in columns)
            cursor.execute(f"CREATE INDEX {quote(old_name)} ON {quote(TABLE)} ({cols})")


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_soft_delete"),
        ("core", "0011_alter_auditevent_tenant"),
        ("processes", "0011_tribunalsync"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("autor", "Autor / Requerente"),
                            ("reu", "Réu / Requerido"),
                            ("terceiro", "Terceiro interessado"),
                            ("assistente", "Assistente"),
                            ("testemunha", "Testemunha"),
                            ("perito", "Perito"),
                            ("mp", "Ministério Público"),
                            ("outro", "Outro"),
                        ],
                        default="autor",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "doc",
                    models.CharField(
                        blank=True, help_text="CPF/CNPJ", max_length=60, null=True
                    ),
                ),
                (
                    "is_client",
                    models.BooleanField(
                        default=False, help_text="Parte representada pelo escritório"
                    ),
                ),
                (
                    "lawyer_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Advogado da parte (quando adverso)",
                        max_length=255,
                    ),
                ),
                (
                    "lawyer_oab",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Inscrição OAB (ex.: SP 123456)",
                        max_length=40,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["role", "name"],
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="tribunalsync",
                    new_name="processes_t_tenant__6d72e9_idx",
                    old_name="processes_tr_tenant_process_idx",
                ),
                migrations.RenameIndex(
                    model_name="tribunalsync",
                    new_name="processes_t_tenant__4c2603_idx",
                    old_name="processes_tr_tenant_syncstatus_idx",
                ),
            ],
            database_operations=[
                migrations.RunPython(_rename_indexes_forward, _rename_indexes_backward),
            ],
        ),
        migrations.AddField(
            model_name="processparty",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="process_parties",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="processparty",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parties",
                to="processes.process",
            ),
        ),
        migrations.AddField(
            model_name="processparty",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process_parties",
                to="core.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="processparty",
            index=models.Index(
                fields=["tenant", "process"], name="processes_p_tenant__95f8a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processparty",
            index=models.Index(
                fields=["tenant", "name"], name="processes_p_tenant__7769a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processparty",
            index=models.Index(
                fields=["tenant", "doc"], name="processes_p_tenant__7afcff_idx"
            ),
        ),
    ]
