# Generated by Django 5.2.15 on 2026-07-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0012_processparty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hearing",
            name="status",
            field=models.CharField(
                choices=[
                    ("agendada", "Agendada"),
                    ("confirmada", "Confirmada"),
                    ("realizada", "Realizada"),
                    ("redesignada", "Redesignada"),
                    ("cancelada", "Cancelada"),
                ],
                default="agendada",
                max_length=12,
            ),
        ),
    ]
