# Generated by Django 5.2.15 on 2026-07-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0013_alter_hearing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="priority",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("media", "Média"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="media",
                max_length=10,
            ),
        ),
    ]
