/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as MasterIndexRouteImport } from './routes/master.index'
import { Route as PortalProcessesRouteImport } from './routes/portal.processes'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalFinancialRouteImport } from './routes/portal.financial'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as OnboardingSetupRouteImport } from './routes/onboarding.setup'
import { Route as OnboardingSelectRouteImport } from './routes/onboarding.select'
import { Route as OnboardingAcceptInviteRouteImport } from './routes/onboarding.accept-invite'
import { Route as MasterUsersRouteImport } from './routes/master.users'
import { Route as MasterPermissionsRouteImport } from './routes/master.permissions'
import { Route as MasterLoginRouteImport } from './routes/master.login'
import { Route as MasterCompaniesRouteImport } from './routes/master.companies'
import { Route as ErrorsSessionExpiredRouteImport } from './routes/errors.session-expired'
import { Route as ErrorsServerRouteImport } from './routes/errors.server'
import { Route as ErrorsForbiddenRouteImport } from './routes/errors.forbidden'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppProcessesRouteImport } from './routes/app.processes'
import { Route as AppPracticeAreasRouteImport } from './routes/app.practice-areas'
import { Route as AppPositionsRouteImport } from './routes/app.positions'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AppHearingsRouteImport } from './routes/app.hearings'
import { Route as AppFinancialRouteImport } from './routes/app.financial'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCompanyRouteImport } from './routes/app.company'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as PortalProcessesIdRouteImport } from './routes/portal.processes.$id'
import { Route as AppProcessesIdRouteImport } from './routes/app.processes.$id'
import { Route as AppCmsLandingRouteImport } from './routes/app.cms.landing'
import { Route as AppCmsBlogRouteImport } from './routes/app.cms.blog'
import { Route as AppClientsIdRouteImport } from './routes/app.clients.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/master/',
  path: '/master/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProcessesRoute = PortalProcessesRouteImport.update({
  id: '/portal/processes',
  path: '/portal/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/portal/messages',
  path: '/portal/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalFinancialRoute = PortalFinancialRouteImport.update({
  id: '/portal/financial',
  path: '/portal/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/portal/documents',
  path: '/portal/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSetupRoute = OnboardingSetupRouteImport.update({
  id: '/onboarding/setup',
  path: '/onboarding/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSelectRoute = OnboardingSelectRouteImport.update({
  id: '/onboarding/select',
  path: '/onboarding/select',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAcceptInviteRoute = OnboardingAcceptInviteRouteImport.update({
  id: '/onboarding/accept-invite',
  path: '/onboarding/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterUsersRoute = MasterUsersRouteImport.update({
  id: '/master/users',
  path: '/master/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterPermissionsRoute = MasterPermissionsRouteImport.update({
  id: '/master/permissions',
  path: '/master/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterLoginRoute = MasterLoginRouteImport.update({
  id: '/master/login',
  path: '/master/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterCompaniesRoute = MasterCompaniesRouteImport.update({
  id: '/master/companies',
  path: '/master/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsSessionExpiredRoute = ErrorsSessionExpiredRouteImport.update({
  id: '/errors/session-expired',
  path: '/errors/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsServerRoute = ErrorsServerRouteImport.update({
  id: '/errors/server',
  path: '/errors/server',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsForbiddenRoute = ErrorsForbiddenRouteImport.update({
  id: '/errors/forbidden',
  path: '/errors/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/app/users',
  path: '/app/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProcessesRoute = AppProcessesRouteImport.update({
  id: '/app/processes',
  path: '/app/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPracticeAreasRoute = AppPracticeAreasRouteImport.update({
  id: '/app/practice-areas',
  path: '/app/practice-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPositionsRoute = AppPositionsRouteImport.update({
  id: '/app/positions',
  path: '/app/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/app/login',
  path: '/app/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHearingsRoute = AppHearingsRouteImport.update({
  id: '/app/hearings',
  path: '/app/hearings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFinancialRoute = AppFinancialRouteImport.update({
  id: '/app/financial',
  path: '/app/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/app/employees',
  path: '/app/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/app/documents',
  path: '/app/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompanyRoute = AppCompanyRouteImport.update({
  id: '/app/company',
  path: '/app/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/app/clients',
  path: '/app/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/app/agenda',
  path: '/app/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProcessesIdRoute = PortalProcessesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalProcessesRoute,
} as any)
const AppProcessesIdRoute = AppProcessesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProcessesRoute,
} as any)
const AppCmsLandingRoute = AppCmsLandingRouteImport.update({
  id: '/app/cms/landing',
  path: '/app/cms/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCmsBlogRoute = AppCmsBlogRouteImport.update({
  id: '/app/cms/blog',
  path: '/app/cms/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/company': typeof AppCompanyRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/financial': typeof AppFinancialRoute
  '/app/hearings': typeof AppHearingsRoute
  '/app/login': typeof AppLoginRoute
  '/app/positions': typeof AppPositionsRoute
  '/app/practice-areas': typeof AppPracticeAreasRoute
  '/app/processes': typeof AppProcessesRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/errors/forbidden': typeof ErrorsForbiddenRoute
  '/errors/server': typeof ErrorsServerRoute
  '/errors/session-expired': typeof ErrorsSessionExpiredRoute
  '/master/companies': typeof MasterCompaniesRoute
  '/master/login': typeof MasterLoginRoute
  '/master/permissions': typeof MasterPermissionsRoute
  '/master/users': typeof MasterUsersRoute
  '/onboarding/accept-invite': typeof OnboardingAcceptInviteRoute
  '/onboarding/select': typeof OnboardingSelectRoute
  '/onboarding/setup': typeof OnboardingSetupRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/financial': typeof PortalFinancialRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/processes': typeof PortalProcessesRouteWithChildren
  '/master/': typeof MasterIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/cms/blog': typeof AppCmsBlogRoute
  '/app/cms/landing': typeof AppCmsLandingRoute
  '/app/processes/$id': typeof AppProcessesIdRoute
  '/portal/processes/$id': typeof PortalProcessesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/company': typeof AppCompanyRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/financial': typeof AppFinancialRoute
  '/app/hearings': typeof AppHearingsRoute
  '/app/login': typeof AppLoginRoute
  '/app/positions': typeof AppPositionsRoute
  '/app/practice-areas': typeof AppPracticeAreasRoute
  '/app/processes': typeof AppProcessesRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/errors/forbidden': typeof ErrorsForbiddenRoute
  '/errors/server': typeof ErrorsServerRoute
  '/errors/session-expired': typeof ErrorsSessionExpiredRoute
  '/master/companies': typeof MasterCompaniesRoute
  '/master/login': typeof MasterLoginRoute
  '/master/permissions': typeof MasterPermissionsRoute
  '/master/users': typeof MasterUsersRoute
  '/onboarding/accept-invite': typeof OnboardingAcceptInviteRoute
  '/onboarding/select': typeof OnboardingSelectRoute
  '/onboarding/setup': typeof OnboardingSetupRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/financial': typeof PortalFinancialRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/processes': typeof PortalProcessesRouteWithChildren
  '/master': typeof MasterIndexRoute
  '/portal': typeof PortalIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/cms/blog': typeof AppCmsBlogRoute
  '/app/cms/landing': typeof AppCmsLandingRoute
  '/app/processes/$id': typeof AppProcessesIdRoute
  '/portal/processes/$id': typeof PortalProcessesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/company': typeof AppCompanyRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/financial': typeof AppFinancialRoute
  '/app/hearings': typeof AppHearingsRoute
  '/app/login': typeof AppLoginRoute
  '/app/positions': typeof AppPositionsRoute
  '/app/practice-areas': typeof AppPracticeAreasRoute
  '/app/processes': typeof AppProcessesRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/errors/forbidden': typeof ErrorsForbiddenRoute
  '/errors/server': typeof ErrorsServerRoute
  '/errors/session-expired': typeof ErrorsSessionExpiredRoute
  '/master/companies': typeof MasterCompaniesRoute
  '/master/login': typeof MasterLoginRoute
  '/master/permissions': typeof MasterPermissionsRoute
  '/master/users': typeof MasterUsersRoute
  '/onboarding/accept-invite': typeof OnboardingAcceptInviteRoute
  '/onboarding/select': typeof OnboardingSelectRoute
  '/onboarding/setup': typeof OnboardingSetupRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/financial': typeof PortalFinancialRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/processes': typeof PortalProcessesRouteWithChildren
  '/master/': typeof MasterIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/cms/blog': typeof AppCmsBlogRoute
  '/app/cms/landing': typeof AppCmsLandingRoute
  '/app/processes/$id': typeof AppProcessesIdRoute
  '/portal/processes/$id': typeof PortalProcessesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/agenda'
    | '/app/clients'
    | '/app/company'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/employees'
    | '/app/financial'
    | '/app/hearings'
    | '/app/login'
    | '/app/positions'
    | '/app/practice-areas'
    | '/app/processes'
    | '/app/users'
    | '/blog/$slug'
    | '/errors/forbidden'
    | '/errors/server'
    | '/errors/session-expired'
    | '/master/companies'
    | '/master/login'
    | '/master/permissions'
    | '/master/users'
    | '/onboarding/accept-invite'
    | '/onboarding/select'
    | '/onboarding/setup'
    | '/portal/documents'
    | '/portal/financial'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/processes'
    | '/master/'
    | '/portal/'
    | '/app/clients/$id'
    | '/app/cms/blog'
    | '/app/cms/landing'
    | '/app/processes/$id'
    | '/portal/processes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/agenda'
    | '/app/clients'
    | '/app/company'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/employees'
    | '/app/financial'
    | '/app/hearings'
    | '/app/login'
    | '/app/positions'
    | '/app/practice-areas'
    | '/app/processes'
    | '/app/users'
    | '/blog/$slug'
    | '/errors/forbidden'
    | '/errors/server'
    | '/errors/session-expired'
    | '/master/companies'
    | '/master/login'
    | '/master/permissions'
    | '/master/users'
    | '/onboarding/accept-invite'
    | '/onboarding/select'
    | '/onboarding/setup'
    | '/portal/documents'
    | '/portal/financial'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/processes'
    | '/master'
    | '/portal'
    | '/app/clients/$id'
    | '/app/cms/blog'
    | '/app/cms/landing'
    | '/app/processes/$id'
    | '/portal/processes/$id'
  id:
    | '__root__'
    | '/'
    | '/app/agenda'
    | '/app/clients'
    | '/app/company'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/employees'
    | '/app/financial'
    | '/app/hearings'
    | '/app/login'
    | '/app/positions'
    | '/app/practice-areas'
    | '/app/processes'
    | '/app/users'
    | '/blog/$slug'
    | '/errors/forbidden'
    | '/errors/server'
    | '/errors/session-expired'
    | '/master/companies'
    | '/master/login'
    | '/master/permissions'
    | '/master/users'
    | '/onboarding/accept-invite'
    | '/onboarding/select'
    | '/onboarding/setup'
    | '/portal/documents'
    | '/portal/financial'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/processes'
    | '/master/'
    | '/portal/'
    | '/app/clients/$id'
    | '/app/cms/blog'
    | '/app/cms/landing'
    | '/app/processes/$id'
    | '/portal/processes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppCompanyRoute: typeof AppCompanyRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppFinancialRoute: typeof AppFinancialRoute
  AppHearingsRoute: typeof AppHearingsRoute
  AppLoginRoute: typeof AppLoginRoute
  AppPositionsRoute: typeof AppPositionsRoute
  AppPracticeAreasRoute: typeof AppPracticeAreasRoute
  AppProcessesRoute: typeof AppProcessesRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ErrorsForbiddenRoute: typeof ErrorsForbiddenRoute
  ErrorsServerRoute: typeof ErrorsServerRoute
  ErrorsSessionExpiredRoute: typeof ErrorsSessionExpiredRoute
  MasterCompaniesRoute: typeof MasterCompaniesRoute
  MasterLoginRoute: typeof MasterLoginRoute
  MasterPermissionsRoute: typeof MasterPermissionsRoute
  MasterUsersRoute: typeof MasterUsersRoute
  OnboardingAcceptInviteRoute: typeof OnboardingAcceptInviteRoute
  OnboardingSelectRoute: typeof OnboardingSelectRoute
  OnboardingSetupRoute: typeof OnboardingSetupRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalFinancialRoute: typeof PortalFinancialRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalProcessesRoute: typeof PortalProcessesRouteWithChildren
  MasterIndexRoute: typeof MasterIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  AppCmsBlogRoute: typeof AppCmsBlogRoute
  AppCmsLandingRoute: typeof AppCmsLandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/master'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/processes': {
      id: '/portal/processes'
      path: '/portal/processes'
      fullPath: '/portal/processes'
      preLoaderRoute: typeof PortalProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/portal/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/financial': {
      id: '/portal/financial'
      path: '/portal/financial'
      fullPath: '/portal/financial'
      preLoaderRoute: typeof PortalFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/portal/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/setup': {
      id: '/onboarding/setup'
      path: '/onboarding/setup'
      fullPath: '/onboarding/setup'
      preLoaderRoute: typeof OnboardingSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/select': {
      id: '/onboarding/select'
      path: '/onboarding/select'
      fullPath: '/onboarding/select'
      preLoaderRoute: typeof OnboardingSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/accept-invite': {
      id: '/onboarding/accept-invite'
      path: '/onboarding/accept-invite'
      fullPath: '/onboarding/accept-invite'
      preLoaderRoute: typeof OnboardingAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/users': {
      id: '/master/users'
      path: '/master/users'
      fullPath: '/master/users'
      preLoaderRoute: typeof MasterUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/permissions': {
      id: '/master/permissions'
      path: '/master/permissions'
      fullPath: '/master/permissions'
      preLoaderRoute: typeof MasterPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/login': {
      id: '/master/login'
      path: '/master/login'
      fullPath: '/master/login'
      preLoaderRoute: typeof MasterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/companies': {
      id: '/master/companies'
      path: '/master/companies'
      fullPath: '/master/companies'
      preLoaderRoute: typeof MasterCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/session-expired': {
      id: '/errors/session-expired'
      path: '/errors/session-expired'
      fullPath: '/errors/session-expired'
      preLoaderRoute: typeof ErrorsSessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/server': {
      id: '/errors/server'
      path: '/errors/server'
      fullPath: '/errors/server'
      preLoaderRoute: typeof ErrorsServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/forbidden': {
      id: '/errors/forbidden'
      path: '/errors/forbidden'
      fullPath: '/errors/forbidden'
      preLoaderRoute: typeof ErrorsForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/app/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/processes': {
      id: '/app/processes'
      path: '/app/processes'
      fullPath: '/app/processes'
      preLoaderRoute: typeof AppProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/practice-areas': {
      id: '/app/practice-areas'
      path: '/app/practice-areas'
      fullPath: '/app/practice-areas'
      preLoaderRoute: typeof AppPracticeAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/positions': {
      id: '/app/positions'
      path: '/app/positions'
      fullPath: '/app/positions'
      preLoaderRoute: typeof AppPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/login': {
      id: '/app/login'
      path: '/app/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/hearings': {
      id: '/app/hearings'
      path: '/app/hearings'
      fullPath: '/app/hearings'
      preLoaderRoute: typeof AppHearingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/financial': {
      id: '/app/financial'
      path: '/app/financial'
      fullPath: '/app/financial'
      preLoaderRoute: typeof AppFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/app/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/app/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/company': {
      id: '/app/company'
      path: '/app/company'
      fullPath: '/app/company'
      preLoaderRoute: typeof AppCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/app/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/app/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/processes/$id': {
      id: '/portal/processes/$id'
      path: '/$id'
      fullPath: '/portal/processes/$id'
      preLoaderRoute: typeof PortalProcessesIdRouteImport
      parentRoute: typeof PortalProcessesRoute
    }
    '/app/processes/$id': {
      id: '/app/processes/$id'
      path: '/$id'
      fullPath: '/app/processes/$id'
      preLoaderRoute: typeof AppProcessesIdRouteImport
      parentRoute: typeof AppProcessesRoute
    }
    '/app/cms/landing': {
      id: '/app/cms/landing'
      path: '/app/cms/landing'
      fullPath: '/app/cms/landing'
      preLoaderRoute: typeof AppCmsLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/cms/blog': {
      id: '/app/cms/blog'
      path: '/app/cms/blog'
      fullPath: '/app/cms/blog'
      preLoaderRoute: typeof AppCmsBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients/$id': {
      id: '/app/clients/$id'
      path: '/$id'
      fullPath: '/app/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsIdRoute: typeof AppClientsIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsIdRoute: AppClientsIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppProcessesRouteChildren {
  AppProcessesIdRoute: typeof AppProcessesIdRoute
}

const AppProcessesRouteChildren: AppProcessesRouteChildren = {
  AppProcessesIdRoute: AppProcessesIdRoute,
}

const AppProcessesRouteWithChildren = AppProcessesRoute._addFileChildren(
  AppProcessesRouteChildren,
)

interface PortalProcessesRouteChildren {
  PortalProcessesIdRoute: typeof PortalProcessesIdRoute
}

const PortalProcessesRouteChildren: PortalProcessesRouteChildren = {
  PortalProcessesIdRoute: PortalProcessesIdRoute,
}

const PortalProcessesRouteWithChildren = PortalProcessesRoute._addFileChildren(
  PortalProcessesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppCompanyRoute: AppCompanyRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppFinancialRoute: AppFinancialRoute,
  AppHearingsRoute: AppHearingsRoute,
  AppLoginRoute: AppLoginRoute,
  AppPositionsRoute: AppPositionsRoute,
  AppPracticeAreasRoute: AppPracticeAreasRoute,
  AppProcessesRoute: AppProcessesRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  BlogSlugRoute: BlogSlugRoute,
  ErrorsForbiddenRoute: ErrorsForbiddenRoute,
  ErrorsServerRoute: ErrorsServerRoute,
  ErrorsSessionExpiredRoute: ErrorsSessionExpiredRoute,
  MasterCompaniesRoute: MasterCompaniesRoute,
  MasterLoginRoute: MasterLoginRoute,
  MasterPermissionsRoute: MasterPermissionsRoute,
  MasterUsersRoute: MasterUsersRoute,
  OnboardingAcceptInviteRoute: OnboardingAcceptInviteRoute,
  OnboardingSelectRoute: OnboardingSelectRoute,
  OnboardingSetupRoute: OnboardingSetupRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalFinancialRoute: PortalFinancialRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalProcessesRoute: PortalProcessesRouteWithChildren,
  MasterIndexRoute: MasterIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  AppCmsBlogRoute: AppCmsBlogRoute,
  AppCmsLandingRoute: AppCmsLandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
