# Generated by Django 5.2.11 on 2026-03-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_installments_soft_delete'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='receivableinstallment',
            new_name='finance_rec_tenant__2e07db_idx',
            old_name='finance_rece_tenant__7c2b0e_idx',
        ),
        migrations.RenameIndex(
            model_name='receivableinstallment',
            new_name='finance_rec_tenant__a0dfc2_idx',
            old_name='finance_rece_tenant__2d2b6d_idx',
        ),
        migrations.AlterField(
            model_name='receivableinstallment',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='aberta', max_length=12),
        ),
    ]
