# Generated by Django 5.2.11 on 2026-03-07 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_department_employee_department_and_more'),
        ('finance', '0004_rename_finance_rece_tenant__7c2b0e_idx_finance_rec_tenant__2e07db_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountspayable',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='accounts.employee'),
        ),
    ]
