# Generated by Django 5.2.15 on 2026-07-12 17:44

from django.db import migrations

# (tabela, nome antigo, nome novo, colunas)
_RENAMES = [
    ("finance_lancamentocontabil", "finance_lan_tenant__data_idx", "finance_lan_tenant__a294ae_idx", ("tenant_id", "data")),
    ("finance_nfse", "finance_nfs_tenant__status_idx", "finance_nfs_tenant__3eac35_idx", ("tenant_id", "status", "created_at")),
    ("finance_nfse", "finance_nfs_tenant__competencia_idx", "finance_nfs_tenant__1388de_idx", ("tenant_id", "competencia")),
]


def _existing(schema_editor, table):
    with schema_editor.connection.cursor() as cursor:
        return {
            name
            for name, info in schema_editor.connection.introspection.get_constraints(cursor, table).items()
            if info.get("index")
        }


def _forward(apps, schema_editor):
    # Idempotente: em SQLite, reconstruções de tabela podem ter descartado o
    # nome explícito do índice (mesmo caso corrigido em processes.0012).
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        for table, old, new, cols in _RENAMES:
            existing = _existing(schema_editor, table)
            if new in existing:
                continue
            if old in existing:
                cursor.execute(f"DROP INDEX {quote(old)}")
            cursor.execute(f"CREATE INDEX {quote(new)} ON {quote(table)} ({', '.join(quote(c) for c in cols)})")


def _backward(apps, schema_editor):
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        for table, old, new, cols in _RENAMES:
            existing = _existing(schema_editor, table)
            if old in existing:
                continue
            if new in existing:
                cursor.execute(f"DROP INDEX {quote(new)}")
            cursor.execute(f"CREATE INDEX {quote(old)} ON {quote(table)} ({', '.join(quote(c) for c in cols)})")


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_nfse_planocontas_lancamentocontabil_lancamentolinha"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="lancamentocontabil",
                    new_name="finance_lan_tenant__a294ae_idx",
                    old_name="finance_lan_tenant__data_idx",
                ),
                migrations.RenameIndex(
                    model_name="nfse",
                    new_name="finance_nfs_tenant__3eac35_idx",
                    old_name="finance_nfs_tenant__status_idx",
                ),
                migrations.RenameIndex(
                    model_name="nfse",
                    new_name="finance_nfs_tenant__1388de_idx",
                    old_name="finance_nfs_tenant__competencia_idx",
                ),
            ],
            database_operations=[migrations.RunPython(_forward, _backward)],
        ),
    ]
